{"uuid": "d29c858a-208d-4785-b046-e33ab4ed2dd7", "children": ["ca646a5e-9d87-4c76-8bcc-53a5a8be9483"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "OSError: [WinError 216] Эта версия \"%1\" не совместима с версией Windows, работающей на этом компьютере. Проверьте сведения о системе, а затем обратитесь к издателю программного обеспечения\n", "trace": "  File \"C:\\Users\\iwmal\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\iwmal\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\iwmal\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Python_study\\Sprint_4\\conftest.py\", line 14, in driver\n    driver = webdriver.Firefox()\n  File \"C:\\Users\\iwmal\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 191, in __init__\n    self.service.start()\n  File \"C:\\Users\\iwmal\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\selenium\\webdriver\\common\\service.py\", line 88, in start\n    self._start_process(self.path)\n  File \"C:\\Users\\iwmal\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\selenium\\webdriver\\common\\service.py\", line 195, in _start_process\n    self.process = subprocess.Popen(\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\subprocess.py\", line 971, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\subprocess.py\", line 1440, in _execute_child\n    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,\n"}, "start": 1679490175149, "stop": 1679490175150}], "start": 1679490175149, "stop": 1679490175196}